### ISSUE TITLE
Add support for Prometheus Exporter

### ISSUE THREAD

**Issue by mfilz** [DBezemer/rpm-haproxy#25]
The Prometheus Exporter PROMEX is an optional module that allows the collection of metrics by [Prometheus](https://promethus.io).
This feature is supported in versions 2.0 onwards. To build it, the make command has to use an additional variable: `EXTRA_OBJS="contrib/prometheus-exporter/service-prometheus.o"`. Adding support for this should be a relatively minor change that safe us from having to edit the spec file by hand for each build.

Please add an option to build haproxy 2.0/2.1 with support for PROMEX.

**Comment by DBezemer** [comment]
@mfilz if you create a pull request that adds this functionality using a feature flag (see LUA for reference implementation) I will test and merge this. The default build is as lean as possible to ensure there is minimal dependency on external modules.

**Comment by mfilz** [comment]
I created two pull requests (for 2.0 and 2.1) as requested. I hope they are up to your standards.

**Comment by mfilz** [comment]
Any updates on this?
