### ISSUE TITLE
Lua support needs root to create RPM

### ISSUE THREAD

**Issue by shadyabhi** [DBezemer/rpm-haproxy#26]
This seems to be happening because of the `make install` step in Lua installation. 

```
make[1]: Entering directory `/home/user/repos/haproxy_testing/rpm-haproxy/lua-5.3.5'
cd src && mkdir -p /usr/local/bin /usr/local/include /usr/local/lib /usr/local/man/man1 /usr/local/share/lua/5.3 /usr/local/lib/lua/5.3
mkdir: cannot create directory ‘/usr/local/man/man1’: Permission denied
mkdir: cannot create directory ‘/usr/local/share/lua’: Permission denied
mkdir: cannot create directory ‘/usr/local/lib/lua’: Permission denied
make[1]: *** [install] Error 1
make[1]: Leaving directory `/home/user/repos/haproxy_testing/rpm-haproxy/lua-5.3.5'
make: *** [build_lua] Error 2
```

**Comment by DBezemer** [comment]
@shadyabhi these steps come from the lua makefile, so any issues you have with them you have to address with the maintainer of the lua packages.

**Comment by shadyabhi** [comment]
@DBezemer Thanks for taking a look. My intent behind this issue was to suggest a way to skip lua install step and modify nginx build params in the spec file to leverage Lua files from the current directory instead of global install. 

The motivation is, why to escalate to root when it isn't necessary.
