### ISSUE TITLE
Compile option USE_PTHREAD_PSHARED=1

### ISSUE THREAD

**Issue by tferic** [DBezemer/rpm-haproxy#30]
Hi
Looking at the resulting haproxy binary, it appears that the option "USE_PTHREAD_PSHARED" is not available.
I wonder if it would make sense to add it, as I would expect that under high load conditions, it may be beneficial.

I tried adding the option to the file SPECS/haproxy.spec:
`%{__make} -j$RPM_BUILD_NCPUS %{?_smp_mflags} ${USE_LUA} CPU="generic" TARGET="linux-glibc" ${systemd_opts} ${pcre_opts} USE_OPENSSL=1 USE_ZLIB=1 ${regparm_opts} ADDINC="%{optflags}" USE_LINUX_TPROXY=1 USE_THREAD=1 USE_PTHREAD_PSHARED=1 USE_TFO=${USE_TFO} USE_NS=${USE_NS} ADDLIB="%{__global_ldflags}"`

I tested the rpm creation, installation and running the resulting haproxy on CentOS 7 and CentOS 8.
However, I did not perform a load test yet.

**Comment by DBezemer** [comment]
@tferic given that USE_PTHREAD_PSHARED would likely not be a good match for most typical uses of HAProxy it's disabled by default to offer best defaults/stability. You are always more than welcome to change the build for your own packages based on my work but given the drawbacks of USE_PTHREAD_PSHARED I won't make this standard defaults for this repository.
