### ISSUE TITLE
`make run-docker` fails on a chcon

### ISSUE THREAD

**Issue by throwaway8787** [DBezemer/rpm-haproxy#35]
2.2 branch. I call `make run-docker`, it errors out with:

```
 ---> Running in b3f62f9c7f8b
Removing intermediate container b3f62f9c7f8b
 ---> 53aca031e4e8
Successfully built 53aca031e4e8
Successfully tagged haproxy-rpm-builder:latest
mkdir -p RPMS
chcon -Rt svirt_sandbox_file_t RPMS
chcon: can't apply partial context to unlabeled file 'RPMS'
make: *** [Makefile:50: run-docker] Error 1
```

**Comment by throwaway8787** [comment]
Things to note:
I'm running ubuntu 20.04. 
I was able to continue by commenting out: https://github.com/DBezemer/rpm-haproxy/blob/2.2/Makefile#L50

**Comment by throwaway8787** [comment]
If it helps I cloned into /tmp, as well.

**Comment by DBezemer** [comment]
@throwaway8787 this would likely occur if you either have SElinux disabled or unavailable since you are on Ubuntu. Commenting out that line will resolve it for you, but I would recommend building the RPMs on an RPM based distribution as there are several RH specific flags in the build spec.
