### ISSUE TITLE
Compile with Specific Openssl

### ISSUE THREAD

**Issue by zerr0s** [DBezemer/rpm-haproxy#41]
Hi,

Is there a way to comile with a specific version of openssl for centos7 ?

Thanks.

**Comment by ruben-herold** [comment]
hi,

I would like to extend the question, is it possible to complile a custom openssl version static into it, like on nginx?

**Comment by ruben-herold** [comment]
I have done some research via google and looking how nginx did this. Form my current point of view after reading https://haproxy.formilux.narkive.com/4w6204L8/build-with-static-openssl It should be possible.:

1. Define a variable which said that a custom openssl shoudl be used and which
2. Before building haproxy we need to extract the openssl source, compile it and install it to a temp. directory:

export LIBSSLBUILD=/tmp/libsslbuild
mkdir $LIBSSLBUILD
cd ~
wget http://www.openssl.org/source/openssl-1.0.1e.tar.gz
tar zxvf openssl-1.0.1e.tar.gz
cd openssl-1.0.1e &&
./config --prefix=$LIBSSLBUILD no-shared
make
make install_sw
make TARGET=linux2628 USE_OPENSSL=1 ADDINC=-I$LIBSSLBUILD/include \
ADDLIB="-L$LIBSSLBUILD/lib -ldl"

**Comment by DBezemer** [comment]
a pull request for a feature like this is always welcome, if you're doing this to get TLS1.3 support please ensure you correctly set the HAproxy config for that as well (in a custom service file for example)
