### ISSUE TITLE
USE _LUA=1 installs lua in /usr/local and don't clean up with make clean

### ISSUE THREAD

**Issue by ruben-herold** [DBezemer/rpm-haproxy#42]
hi,

after make USE_LUA=1 I found out that this not only build lua, it also installed it into 
/usr/local and a make clean does not remove it. 

Why can't it be installed in a temp. directory and removed after build.

**Comment by DBezemer** [comment]
@ruben-herold of course it can be installed/compiled into a temp directory and removed after build, feel free to make a pull request that does this :)
