### ISSUE TITLE
VERSION selection should filter for MAINVERSION

### ISSUE THREAD

**Issue by sharumpe** [DBezemer/rpm-haproxy#43]
When building 1.8, I came across the case where the VERSION returned is `xceliance-20100614` instead of `1.8.30`.

I would like to suggest that the pipeline include a `grep "^${MAINVERSION}"` before the `sort -rV` to limit responses to just the intended MAINVERSION.  This is what I'm doing in a fork and it seems to be working as intended.

Thank you for providing this repo which has saved me so much time.

**Comment by DBezemer** [comment]
hmm this seems to be a recent development where the git tags are polluted with both customer specific and haproxy EE tags in their git, thanks for catching this and I'll see what filter I can add to prevent this.
