### ISSUE TITLE
Log lines appearing with wrong prefix

### ISSUE THREAD

**Issue by timwhitlock** [DBezemer/rpm-haproxy#46]
I don't know if this is a bug or change in HAProxy, or something I've done wrong, but I thought I'd check here first because this repo is what I've used to build my binaries. I'm wondering if perhaps there is a build option that affects the following behaviour.

---
Upgrading recently from some old 1.x version of HAProxy to version 2.5.1 (and leaving the config file unchanged) I noticed my log files have lost the `haproxy[%pid]` prefix and instead have an empty space:

So with this directive:

    log-format "[%[date,ltime(%Y-%m-%dT%H:%M:%S%z)]] %{+Q}o %{-Q}ci %r %ST"

I now get a line like this with a blank space:
    
     [2022-02-09T07:27:48+0000] 127.0.0.1 "GET / HTTP/1.1" 301
    ^

I can add the prefix back in with this:

     log-format "haproxy[%pid]: [%[date,ltime(%Y-%m-%dT%H:%M:%S%z)]] %{+Q}o %{-Q}ci %r %ST"

But I still get the blank space.

Any idea what's going on?

Update: Casting my mind back it looks like I must have modified your Makefile to bump the version up to 2.5. Although I don't remember doing this, I must have done because I see your releases only go up to 2.4. Is this likely related?

**Comment by DBezemer** [comment]
@timwhitlock it's unlikely that bumping the Makefile is an issue, but the log format and what information is written to logs is determined by HAProxy itself, so you're better off asking for help in the mailing lists or forums for HAProxy as this repo only aims to build RPM files.
