### ISSUE TITLE
backend server ssl health fails with backend server running tls v1.3

### ISSUE THREAD

**Issue by wong604** [DBezemer/rpm-haproxy#48]
**haproxy.cfg:**
global
    log         /dev/log local0
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon
    stats socket /var/lib/haproxy/stats

    ssl-default-bind-ciphers PROFILE=SYSTEM
    ssl-default-server-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-server-ciphers ECDH+AESGCM:ECDH+CHACHA20:ECDH+AES256:ECDH+AES128:!aNULL:!SHA1:!AESCCM
    tune.ssl.default-dh-param 2048

defaults
    default-server  ca-file /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
    log  global
    mode  http
    timeout  http-request 10s
    timeout  queue 1m
    timeout  connect 10s
    timeout  client 1m
    timeout  server 1m
    timeout  check 10s

resolvers local_resolv
    parse-resolv-conf
    hold valid 10s

frontend main
    bind *:443 ssl crt /etc/ssl/certs/fcm.googleapis.com.pem
    mode http
    default_backend fcm

backend fcm
    mode http
    server fcm fcm.googleapis.com:443 resolvers local_resolv resolve-prefer ipv4 check ssl verify required

ha log:
[NOTICE]   (27649) : New worker #1 (27651) forked
[WARNING]  (27651) : Server fcm/fcm is DOWN, reason: Layer6 invalid response, info: "SSL handshake failure", check duration: 20ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[NOTICE]   (27651) : haproxy version is 2.4.17-9f97155
[NOTICE]   (27651) : path to executable is /usr/sbin/haproxy
[ALERT]    (27651) : backend 'fcm' has no server available!

The problem can be bypassed by setting verify required to verify none. However, this does not meet our security standard.

curl -v gives:
:::
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
:::

but including the cipher suite TLS_AES_256_GCM_SHA384 and cipher ECDH+AES256 did not help.

The problem does not exist on EL7 which does not only use TLS 1.2.

**Comment by wong604** [comment]
sorry, the indentation for the haproxy.cfg file is not work. I re-enter it here:

global

    log         /dev/log local0

    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon

    stats socket /var/lib/haproxy/stats

    ssl-default-bind-ciphers PROFILE=SYSTEM
    ssl-default-server-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-server-ciphers ECDH+AESGCM:ECDH+CHACHA20:ECDH+AES256:ECDH+AES128:!aNULL:!SHA1:!AESCCM
    tune.ssl.default-dh-param 2048


defaults

    default-server  ca-file /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
    log  global
    mode  http
    timeout  http-request 10s
    timeout  queue 1m
    timeout  connect 10s
    timeout  client 1m
    timeout  server 1m
    timeout  check 10s


resolvers local_resolv

    parse-resolv-conf
    hold valid 10s

frontend main

    bind *:443 ssl crt /etc/ssl/certs/fcm.googleapis.com.pem
    mode http
    default_backend fcm

backend fcm

    mode http
    server fcm fcm.googleapis.com:443 resolvers local_resolv resolve-prefer ipv4 check ssl verify required

**Comment by DBezemer** [comment]
@wong604 this is not the repo to get support for HAProxy itself. My suspicion is that you need check-sni instead of regular check as the upstream host uses SNI. In addition you're unlikely to have valid certs for fcm.googleapis.com but instead are using self-signed certificates so there's a whole rabbithole of potential issues with combining that with TLS1.3, and your local DNS overrides etc.

**Comment by wong604** [comment]
I already tried that. It does not mark the backend server to be problematic, but it still will not work until you turn it off completely. My workaround is to use EL7 with TLS V1.2 and the most secured ciphers available for 1.2. This problem needs to be worked on. I hope that someone in the opensource community can fix it later some day.


Joseph Wong, Enterprise Systems Administrator
P: 604-215-4820 / C: 604-218-2052
ecomm911.ca<https://www.ecomm911.ca/> @EComm911_info<https://twitter.com/ecomm911_info>
CONFIDENTIALITY NOTICE: This email and any attachments are only for the use of the intended recipient and must not be distributed, disclosed, used or copied by or to anyone else. This transmission may contain confidential or privileged information, and the sender does not waive any related rights, protection or obligations in connection with such materials. The unauthorized use or disclosure of this material may be unlawful and result in legal action or other sanctions. If you have received this email in error please immediately contact the sender by return email and delete all copies of this email and any attachments.
